### ISSUE TITLE
Use SPI for connecting master/slave boards.

### ISSUE THREAD

**Issue by Nettech15** [Nettech15/STM32CubeIDE-Daisy-Seed-Synthesizer#7]
Use SPI Interface for connecting master/slave boards. Serial at 230400 is simply too slow and taking up too much MPU bandwidth. It is affecting the quality of the sound engine, and the boards crash and hang way too much. Serial buffering does not even solve the problem.

**Comment by SnazzyBlanket** [comment]
Wow that is not good — what is the use case you are attempting ? I ask because I was interested in doing communication of non audio data ( preset sequence or parameters interrupts clock signals etc.) from an AVR to or from the Daisy

**Comment by Nettech15** [comment]
Yes, it was a bad decision on my part to implement serial communication between master and slave boards. I should have been aware of the timing and throughput issues that would occur. I will bring this feature back with an 8-bit parallel interface (with 2 bits of handshake lines added as well). Interrupt-driven SPI is an option, but a parallel interface is less time consuming to implement. Unfortunately, a parallel interface will be proprietary, and require 10 wires between master and slave boards. Also, at high speeds and longer distances, these wires will become transmission lines, and will probably need to be tuned with passive components to prevent timing errors.

**Comment by Nettech15** [comment]
Parallel, SPI, and even I2C Master/Slave test projects work fine, but as soon as I integrate these changes into my Synth project code, the code breaks. I think at this point it is just an MPU overload issue. I will just leave this issue closed for now.
